channels:
  # Define conda channels here. 
  - conda-forge

dependencies:
  # Define conda packages here. 
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search  
  - python=3.10.12
  - robocorp-truststore=0.8.0
  - pip=23.2.1 

  - pip:
    - rpaframework==28.5.1        # https://rpaframework.org/releasenotes.html
    - robocorp==2.0.1             # https://pypi.org/project/robocorp
    - robocorp-browser==2.3.3     # https://pypi.org/project/robocorp-browser
    - requests==2.31.0
